baseURL: https://sarru1291.github.io/
languageCode: en-us
theme: "toha"
publishDir: "docs"

DefaultContentLanguage: "en"
# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    title: "Sarvottam Kumar"
    weight: 1
  hi:
    languageName: Hindi
    title: "सर्वोत्तम कुमार"
    weight: 2

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-148987382-1

# Enable Disqus forum
# disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  description: "Sarvottam Kumar is an assistant software engineer at TCS with interest and experience in blockchain, react.js, angular, nodejs, java and flutter development. Sarvottam Kumar also works as freelance Linux and open source writer, and developer."
  # background image of the landing page
  background: /images/site/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # GitHub repo URL of your site
  gitRepo: https://github.com/sarru1291/sarru1291.github.io

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true

# [permalinks]
#   posts = "/:06/:1/:2/:title/"