baseURL: https://sarru1291.github.io/
languageCode: en-us
theme: "toha"
publishDir: "docs"

title: "Sarvottam Kumar"
DefaultContentLanguage: "en"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable Google Analytics
googleAnalytics: UA-148987382-1

# Enable Disqus forum
# disqusShortname: does-not-exist

# Enable global emoji support
enableEmoji: true


# [languages]

#   [languages.en]
#   title = "Sarvottam kumar"
#   weight = 2
#   contentDir = "content/en"
#   languageName = "English"
#   [[languages.en.menu.main]]
#   url    = "/"
#   name   = "Home"
#   weight = 1

#   [languages.hi]
#   title = "सर्वोत्तम कुमार"
#   weight = 1
#   contentDir = "content/hi"
#   languageName = "हिन्दी"
#   [[languages.hi.menu.main]]
#   url    = "/"
#   name   = "मुख्य"
#   weight = 1



# Custom parameters
params:
  # Copyright Notice
  copyright: © 2020 Copyright.

  # Meta description for your site.  This will help the search engines to find your site.
  description: Portfolio and personal blog of Sarvottam Kumar.

  # background image of the landing page
  background: "assets/images/background.jpg"

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  # It will be default to the theme logos if not provided.
  logo:
    main: /assets/images/profile_picture_140x140.svg
    inverted: /assets/images/profile_picture_140x140.svg

  # GitHub repo URL of your site
  gitRepo: https://github.com/sarru1291/sarru1291.github.io

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  customMenus:
  - name: Notes
    url: https://hossainnotes.netlify.app/docs/example/

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true

  # some information about you
  author:
    name: "Sarvottam Kumar"
    nickname: "Sarvottam Kumar"
    image: "assets/images/profile_picture_140x140.svg"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "sarru1291@gmail.com"
      phone: "+919958938566"
      twitter: "https://twitter.com/sarru1291"
    # a summary of what you do
    summary:
    - I am a Developer
    - I work with Go
    - I love to work with some fun projects

# [permalinks]
#   posts = "/:06/:1/:2/:title/"